### ISSUE TITLE
"This extension violates the Chrome Web Store policy."

### ISSUE THREAD

**Issue by Eisys** [danieljbingham/google-image-sizer#12]
Chrome now gives that warning. What's up with that?

**Comment by danieljbingham** [comment]
Hi @Eisys,

Thanks for bringing that to my attention! I believe it should all be fixed now, I pushed an update to the chrome store and it seems to be working now (you might need to manually update). Let me know if there are still any issues.

Essentially an extra unused permission was declared in the manifest - it was used in an old version of the extension, but no longer needed in the current version. The extension was flagged for requesting that permission without using it, but now that I've removed it the problem should be fixed.

Daniel

**Comment by Eisys** [comment]
Tried updating all extensions, nothing. I then removed the extension and added it again. Still gives the error. I'm guessing the update takes a while to get pushed to the store.

Or I'm misunderstanding by what you mean by 'update manually'

**Comment by Procyon-b** [comment]
> Or I'm misunderstanding by what you mean by 'update manually'

I think he means that you can ask chrome to check for updates. On the extension page, enable "Developer mode" and click "Update"

**edit**
The version number on the webstore is currently: 1.0.4

**Comment by Eisys** [comment]
Yeah I did that but since, as you said, the version nr is still the same so it has no available update yet.

**Comment by Procyon-b** [comment]
Yes "chrome web store" is an pain in the ...
I have a couple of extensions that need an update, but I have so much of permissions to get through that I don't have the courage. (Unless it has changed, the rejection of an update is not helpful. No clear reason is given. Even when asked.)

**Comment by Procyon-b** [comment]
Looking at my extension update log for "Image Search Sizer", v1.0.4 was installed yesterday (2021/08/26 14:18:33), and the previous version v1.0.3.6 , 1y 174d ago (2020/03/05 15:18:59)

**Comment by danieljbingham** [comment]
Maybe try reinstalling again, I just tried it now to check and it successfully gave me 1.0.4 which is working for me as it was before

**Comment by giosepeluiz** [comment]
Same problem with Microsoft Edge.

![image](https://user-images.githubusercontent.com/16369337/131190982-e44043f5-2013-4019-81a4-dde98299a3e0.png)

**Comment by Procyon-b** [comment]
I'm not using the extension (it is installed but disabled). Since it's only a userscript, I run it in tampermonkey.
If you have tampermonkey installed, it's as easy as going to the "Code" tab of this repository, then "run.user.js" in the list, and then "Raw" button.

I can confirm that chrome disables the extension with a message on the extensions list page.

**Comment by Procyon-b** [comment]
Got updated to 1.0.5. So far no error message.

**Comment by Procyon-b** [comment]
Chrome disables the extension, and the message is displayed on the extension manager page.

**Comment by danieljbingham** [comment]
This is really strange, I'm getting absolutely no warning about it on the Chrome Developer Dashboard so I have no way of knowing what the actual issue is. I'll keep investigating

>

**Comment by Procyon-b** [comment]
I remember having this issue with an extension, but the extension was also removed from the webstore.
What is strange here is that the extension is still there...

**Comment by danieljbingham** [comment]
I got in touch with Google and they weren't sure why it had been flagged this time, so apparently, they've cleared it up. It's working now, but I'll give it a few hours to check everything remains fine before closing this issue.

**Comment by Eisys** [comment]
> I got in touch with Google and they weren't sure why it had been flagged this time, so apparently, they've cleared it up. It's working now, but I'll give it a few hours to check everything remains fine before closing this issue.

You contacted Google, got a reply in a timely manner and they even said they'd do something about your problem?? This is an impossible miracle..

#FuckGoogle aside, unfortunately I personally am still getting the error. 10 minutes ago I uninstalled and reinstalled the extension and now it's disabled by Chrome again with the same warning. Version 1.0.5

**Comment by Procyon-b** [comment]
Started a computer 15min ago, chrome is running, extension is enabled (at startup) and no message displayed so far.
Stay tuned...

**Comment by Procyon-b** [comment]
Extension disabled.  :(

**Comment by danieljbingham** [comment]
Thought Google's quick response might be too good to be true, back to the drawing board then.

**Comment by Eisys** [comment]
Well, seems that Google might have done something after all. Or did you fix something?

Either way, it's staying active now and doesn't give any errors. Version 1.0.5 still.

**Comment by Procyon-b** [comment]
Maybe it takes time for this setting to propagate to the browser.
